### ISSUE TITLE
Some question of the paper

### ISSUE THREAD

**Issue by Mr2er0** [DC1991/FS-Net#1]
Hello, thank you for your great work! I have some questions about the content of the paper.

The data enhancement method in this paper is online. How to understand the meaning of online. My understanding is that if the three-dimensional model of an object is changed, the information in the two-dimensional image will also be changed. In this case, does the information in the two-dimensional image also need to be changed? When did you change the three-dimensional model, and how did you realize it online?

**Comment by DC1991** [comment]
Thanks for your interest in the paper.  As shown in Figure 2 of the paper. We only apply the 3D deformation on the point cloud transformed from the cropped depth. Therefore, we do not need to consider the change of the 2D image.  Online in this paper means we apply the 3D deformation operation during the training stage rather than preparing the deformed point cloud before the training.
